### PR TITLE
Fix 468: ERROR - 'str' object has no attribute 'read'

### LINKED ISSUE #468: Ceph health check fails with error - ERROR - 'str' object has no attribute 'read'
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1619152243856/check-ceph-health_1.log

While running upgrade_containerized on a rhel-8 cluster for 4.2z1 RC, the ceph health check failed.

2021-04-23 01:47:52,747 - exec - ERROR - 'str' object has no attribute 'read'

### PR DESCRIPTION
**Pull request by psathyan**
# Description

When `long_running` argument is enabled then the return type is string which has caused the breaking mentioned in #468 

This PR modifies the default behavior to check the type before decoding.

Closes #468 

### Logs:
4: http://magna002.ceph.redhat.com/ceph-qe-logs/psathyan/i468/4/ 
5: http://magna002.ceph.redhat.com/ceph-qe-logs/psathyan/i468/5/

Signed-off-by: Pragadeeswaran Sathyanarayanan <psathyan@redhat.com>

### CODE REVIEW

File: tests/misc_env/exec.py [hunk 1]
```diff
@@ -27,7 +29,10 @@ def exec_command(node, **kwargs: Any) -> Tuple:
         CommandFailed   when there is an execution failure
     """
     out, err = node.exec_command(**kwargs)
-    return out.read().decode(), err.read().decode()
+
+    out = out.read().decode() if isinstance(out, ChannelFile) else out
```
Comment (sunilkumarn417) [inline tests/misc_env/exec.py:33]: Can we avoid checking `ChannelFile`, instead going with `str` would be good.

Comment (sunilkumarn417) [reply tests/misc_env/exec.py:33]: this way, we could avoid import statement also.

Comment (psathyan) [reply tests/misc_env/exec.py:33]: In exec_command, we are doing `out.read()` which could return a `str` or `bytes` but mostly `str` in our case. As the need to perform `read` is for a base file type object, I went with this implementation... in future, if we change the return value, I didn't want to break it...

**Review by sunilkumarn417 — APPROVED** [review]
